[package]
name = "starplayer"
version = "0.1.0"
edition = "2024"

[lib]
name = "starplayer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "starplayer"
path = "src/main.rs"

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
rusqlite = { version = "0.33", features = ["bundled"] }
walkdir = "2"
uuid = { version = "1", features = ["v4"] }

[build-dependencies]
tauri-build = { version = "2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
